### ISSUE TITLE
eslint webpack resolution

### ISSUE THREAD

**Issue by alexdilley** [chrisvfritz/vue-monolith-example#1]
Happy new year!

I got me a fork: alexdilley/vue-monolith-example@8f8b176.

This is a checkout of your repo with `yarn upgrade` applied (to dance around the `flatmap-stream`  shenanigans) and what I believe is a minor bugfix: the `eslint` [command](https://github.com/chrisvfritz/vue-monolith-example/blob/master/package.json#L23) requires a glob argument.

In addition, I'm attempting to move a project – initialised off your enterprise boilerplate – to this mono repo format. But I'm finding that eslint falls flat on its face trying to resolve any defined Webpack aliases. I've demonstrated this on my fork by adding the eslint rule (from Airbnb's config, which I personally utilise) to error on declaration of unresolvable imports, and by aliasing the `src/views` directory. It seems that, although a dev server can be spun up, aliases aren't being resolved, and eslint raises errors.

On investigation, running:
```
./node_modules/.bin/vue-cli-service inspect > output.js
```
from the root directory yields only a base/plain Vue CLI webpack config, whilst the same command from within the `frontend` directory outputs what you'd expect (i.e. includes the defined alias). My guess is that eslint is interpreting the webpack config like the former.

I have found that within my project moving `vue.config.js` to the root gets things to "work", but that feels like the wrong solution because the file belongs to `frontend`. I have my suspicions that Vue CLI isn't set up to work with `vue.config.js` placed anywhere other than the root directory, however (hence why I've had some success here).

I've also tried adding this to the eslint configuration:

```js
settings: {
  'import/resolver': {
    webpack: {
      config: path.join(
        __dirname,
        'node_modules/@vue/cli-service/webpack.config.js'
      ),
    },
  },
},
```

But to no avail. Ideally you'd want to do this from the context of `frontend`'s `node_modules` but, of course, with yarn workspaces everything's hoisted up to the root. (And I have tried using the `nohoist` option there with zero success.)

This is really more of a long shot: do you have any ideas how to work this? Since I got the impression this repo came about to demonstrate a pattern you've employed before, have you on your travels turned a vue-enterprise-boilerplate-esque (where webpack aliases were likely to have been defined) into a mono repo alongside a backend and hence come across this issue? Out of interest, do you [still] advocate this mono repo scheme generally (probably a stupid question given this repo exists!)? I really like the idea of not jumping between two terminal instances when managing dev environments, as well as having a single commit history.

**Comment by alexdilley** [comment]
Hey @chrisvfritz. Pinging this in case you missed it. Not urgent, mind :)

**Comment by chrisvfritz** [comment]
I've never personally had a need to investigate this problem, since modules not resolving causes a build failure, so I already get warnings. It's possible that a `jsconfig.json` like the one automatically generated in vue-enterprise-boilerplate would solve the problem though. I'm not sure if ESLint looks for that (it probably should!). 🙂
